### PR TITLE
Autocapture fixed

### PR DESCRIPTION
**Pull request by adityarathoreworld**
Changes made to controller>front>validation.php
fixed: missing currency field
Effect: resolved error bad request : missing currency field, creating orders, and capturing payment in multi currency.
@ramth05  helps me to find way to get cart currency thanks mate.
updated new validation php file here
[validation.zip](https://github.com/razorpay/razorpay-prestashop/files/3874696/validation.zip)

### CODE REVIEW

**Comment by harman28** [comment]
@adityarathoreworld The PR currently contains a lot of other changes too, probably because master is being backmerged into a different branch. Could you clear this up please?

**Comment by adityarathoreworld** [comment]
Sir i am concerned about 1.6 prestashop version as i am using same and having issue with it for accepting orders when contacted earlier came to know only 1.7 is supported by razorpay support do a quick fix i mentioned save me a big time. It will allow anyone using presta1.6 to accept payment on razorpay which otherwise is not working and throwing error i mentioned above.
Razorpay v1.3.1 is the module i made these changes for.

**Comment by harman28** [comment]
The PR you have raised does not add capture support for PS1.6 (Razorpay 1.3.0). If you want to attempt adding capture support, fork off from this branch: [master-1.6](https://github.com/razorpay/razorpay-prestashop/tree/master-1.6) and raise a PR. We will review it, and release it as well.

For now I'm closing this PR. Have responded to your mail as well, let's see if we can reach a solution that works for you.

**Comment by sskathait** [comment]
To add Auto-capture support of PS1.6 already raised. [Link](https://github.com/razorpay/razorpay-prestashop/issues/32). Hopefully team will consider and do the needful.

**Pull request closed without merging**
